crystal-ball/componentry

.eslintrc.js, lib/Drawer/Drawer.spec.jsx, lib/Drawer/__snapshots__/Drawer.spec.jsx.snap, lib/Dropdown/Dropdown.spec.jsx, lib/Dropdown/__snapshots__/Dropdown.spec.jsx.snap, lib/State/State.spec.jsx, lib/State/__snapshots__/State.spec.jsx.snap, lib/State/index.js, lib/State/withState.jsx, lib/component-factories/state-container.jsx, lib/component-factories/state-content.jsx, lib/component-factories/state-trigger.jsx, lib/index.js, lib/utils-test/activation-tests.jsx, lib/utils-test/dt.js, package.json
Create a suite of general purpose activation tests. Add to State, Dropdown and Drawer components.
=> Dropdown testing ✅

lib/Modal/Modal.jsx, styles/bootstrap/_modal.scss
Endowing modals with the ability to scroll off the page.  Go forth and do no harm.
=> Support for modals with large amounts of content

package-lock.json, package.json, styles/_bootstrap.scss, styles/bootstrap/_alert.scss, styles/bootstrap/_buttons.scss, styles/bootstrap/_close.scss, styles/bootstrap/_custom-forms.scss, styles/bootstrap/_input-group.scss, styles/bootstrap/_modal.scss, styles/bootstrap/_navbar.scss, styles/bootstrap/_pagination.scss, styles/bootstrap/_popover.scss, styles/bootstrap/_print.scss, styles/bootstrap/_reboot.scss, styles/bootstrap/_tooltip.scss, styles/bootstrap/_variables.scss, styles/bootstrap/bootstrap-grid.scss, styles/bootstrap/bootstrap-reboot.scss, styles/bootstrap/bootstrap.scss, styles/bootstrap/mixins/_breakpoints.scss, styles/bootstrap/mixins/_buttons.scss, styles/bootstrap/mixins/_forms.scss, styles/bootstrap/mixins/_grid-framework.scss, styles/bootstrap/mixins/_hover.scss, styles/bootstrap/mixins/_list-group.scss, styles/bootstrap/utilities/_borders.scss, styles/bootstrap/utilities/_display.scss
Keeping some componentry modifications for headers of modals, alerts so that they can use flexbox.  Keeping our new class `dropdown-content` for dropdowns.
EG. This PR fixes #XX by doing some important safety checking, etc etc...
* ✨ Totally radical new feature that you're going to love
* 🐛 Fixed this broke code
* ✅ Added tests to prevent this happening in the future
* 📝 Wrote some rad documentation
=> Adding Bootstrap v4.0

lib/Active/__snapshots__/Active.spec.jsx.snap, lib/Drawer/__snapshots__/Drawer.spec.jsx.snap, lib/Dropdown/__snapshots__/Dropdown.spec.jsx.snap, lib/Dropdown/dropdown.scss, lib/Popover/__snapshots__/Popover.spec.jsx.snap, lib/Tooltip/__snapshots__/Tooltip.spec.jsx.snap, lib/component-factories/active-container.jsx, lib/utils/dom.js
Fixing dropdown so that there is better blur handling.  In the past, you could have multiple dropdowns open, and worse, the might overlap.  This fixes all that, and also gives a more sensible click area
* 🐛 Fixed dropdown click area and blur event
=> Dropdown click area

styles/bootstrap/_modal.scss
* 🐛 replace .modal-open class with .no-scroll class in our modal stylesheet
=> Fix bug: modals not scrolling

styles/bootstrap/_modal.scss
* 🐛 replace .modal-open class with .no-scroll class in our modal stylesheet
=> fix(styles): get modals to scroll again

package.json
Closes #27
EG. This PR fixes #XX by doing some important safety checking, etc etc...
* ✨ Totally radical new feature that you're going to love
* 🐛 Fixed this broke code
* ✅ Added tests to prevent this happening in the future
* 📝 Wrote some rad documentation
=> chore(package): update react to version 16.3.1

package.json
Closes #26
EG. This PR fixes #XX by doing some important safety checking, etc etc...
* ✨ Totally radical new feature that you're going to love
* 🐛 Fixed this broke code
* ✅ Added tests to prevent this happening in the future
* 📝 Wrote some rad documentation
=> chore(package): update react-dom to version 16.3.1

styles/initialize/_reboot.scss
Refactors button and form element reboot styles to a single set per element. Although this is slightly less maintainable, this file won't change much and it simplifies debugging applied styles for these elements.
=> refactor: condense reboot styles to single set per element

demo/components/HomeScreen/HomeScreen.js, guides/Architecture.md, package.json, src/ThemeProvider/ThemeProvider.js, src/Type/Type.js, src/elem-factory.js, src/utils-test/element-tests.js, src/utils/clean-props.js, src/utils/spacing.js
PR adds default spacing utility handlers to all elements to simplify passing custom margin and padding to elements inline.
=> feat(components): add library space utils 🎉

src/Modal/modal.scss, styles/theme/_variables.scss
PR adds some additional modal theming variables.
=> feat: add theming for modal header, title and footer

src/Dropdown/Dropdown.js, src/Flex/Flex.js, src/Popover/Popover.js, src/ThemeProvider/ThemeProvider.js, src/Tooltip/Tooltip.js, src/active-container-factory.js, src/index.js, src/utils/transfer-statics.js, src/withTheme.js
Fixes an issue where setting defaultProps breaks the ability to set library defaults with context. All defaultProps are removed from library source, only configuration params are used.
=> fix: remove library source defaultProps instances

src/utils/spacing.js
Fixes the space util missing string literals for x and y space props.
=> fix: space util x+y handlers

.prettierignore, demo/components/ComponentsScreen/Screens/Forms.md, demo/lib/routes-map.js, src/FormGroup/FormGroup.js, src/FormGroup/form-group.scss, src/Input/Input.js, src/Input/input.scss, src/index.js, styles/_components.scss, styles/theme/_input.scss, styles/theme/_variables.scss
Adds an `Input` wrapper component with Field, Label, Description, and Error subelements.
=> feat: add input component

.eslintrc.js, src/Active/Active.js, src/Drawers/Drawers.js, src/Dropdown/Dropdown.js, src/Popover/Popover.js, src/Tab/Tab.js, src/Tooltip/Tooltip.js, src/active-container-factory.js
It's possible to use statics from within render, which simplifies the args passed to the content container factory.
=> refactor: improve statics assignments

CHANGELOG.md, demo/components/HomeScreen/HomeScreen.js, demo/components/HomeScreen/homescreen.scss, src/utils/componentry.js, styles/atomic/_borders.scss
=> feat: add width, height bg and border atomic styles

demo/components/HomeScreen/HomeScreen.js, src/Block/Block.d.ts, src/Block/Block.js, src/index.d.ts, src/index.js
Adds a Block component to complement the Flex component for working with display `block` and `inline-block` elements.
=> feat: add Block component

.travis.yml
Updates the Travis config file to latest 🔮 Project standards.
=> Chore: Update Travis configs 🆙

README.md
Logo src and badge content updates to README.
=> Docs: Update Readme logo and badges 📝

src/Block/Block.js, src/Block/Block.spec.js, src/Block/Block.stories.js, src/Block/__snapshots__/Block.spec.js.snap, src/Button/Button.stories.js, src/Flex/Flex.js, src/Flex/Flex.spec.js, src/Flex/Flex.stories.js, src/Flex/__snapshots__/Flex.spec.js.snap
Block and Flex components looking 👍 👍
=> Chore: Fix tests and storybooks for Flex and Block components ✨

src/Anchor/anchor.scss, src/Button/button.scss, src/Header/header.scss, styles/_reboot.scss, styles/atomic/_text.scss, styles/theme/_variables.scss
EG. This PR fixes #XX by doing some important safety checking, etc etc...
* ✨ Totally radical new feature that you're going to love
* 🐛 Fixed this broke code
* ✅ Added tests to prevent this happening in the future
* 📝 Wrote some rad documentation
=> Chore: Update reboot file 🔧

src/Header/Header.js, src/Header/__snapshots__/Header.spec.js.snap, src/Header/header.scss, src/Text/text.scss, styles/_reboot.scss, styles/content/_forms.scss, styles/theme/_button.scss, styles/theme/_input.scss, styles/theme/_variables.scss, styles/utility/_text.scss
- Adds a `.header` class for shared header styles
- Adds header letter-spacing and text-transform theming
- Adds a `$paragraph-max-width`
=> Update: Add header font theming options ✨

src/Alert/Alert.js, src/Anchor/Anchor.js, src/Block/Block.js, src/Button/Button.js, src/Card/Card.js, src/Close/Close.js, src/Flex/Flex.js, src/FormGroup/FormGroup.js, src/Heading/Heading.js, src/Icon/Icon.js, src/Input/Input.js, src/ListGroup/ListGroup.js, src/Media/Media.js, src/Modal/Modal.js, src/Nav/Nav.js, src/Popover/Popover.js, src/Tabs/Tabs.js, src/Text/Text.js, src/Theme/Theme.js, test/element-tests.js
_Adds a `displayName` to every component_
This change makes debugging Componentry components in the React devtools a much better experience for production builds.
=> Update: Add displayName for production React devtools debugging 💯

.storybook/config.js, src/Alert/Alert.stories.mdx, src/Anchor/Anchor.stories.mdx, src/Button/Button.stories.mdx, src/FormGroup/FormGroup.stories.mdx, src/Heading/Heading.stories.mdx, src/Input/Input.stories.mdx, src/Popover/Popover.stories.mdx, src/Tabs/Tabs.stories.mdx, src/Text/Text.stories.mdx, src/Tooltip/Tooltip.stories.mdx, src/story-resources.js, src/styles/utility/_backgrounds.stories.mdx, src/styles/utility/_borders.stories.mdx, src/styles/utility/_spacing.stories.mdx, src/styles/utility/_tables.stories.mdx, src/styles/utility/_typogrpahy.stories.mdx, src/styles/utility/_vertical-align.stories.mdx
_Upgrades override process for default Storybook components_
Uses the Storybook config to override the Storybook Styled Components. _(this is needed to be able to pass classNames to elements 😐)_
=> Chore: Remove ElementsProvider

src/hooks.js
_Fixes `useVisble` setting state after unmounting_
The calls to request animation frame and setTimeout meant that it was possible for components using this hook to attempt to setState after unmounting 😱
=> Fix: Dont set state after unmounting ✓

src/Alert/Alert.js, src/Alert/__snapshots__/Alert.spec.js.snap, src/Anchor/Anchor.js, src/Badge/Badge.js, src/Block/Block.js, src/Button/Button.js, src/Card/Card.js, src/Close/Close.js, src/Flex/Flex.js, src/FormGroup/FormGroup.js, src/Heading/Heading.js, src/Icon/Icon.js, src/Input/Input.js, src/ListGroup/ListGroup.js, src/Modal/Modal.js, src/Modal/__snapshots__/Modal.spec.js.snap, src/Nav/Nav.js, src/Popover/Popover.js, src/Tabs/Tabs.js, src/Text/Text.js, src/active-container-factory.js, src/active-content-factory.js, src/active-trigger-factory.js, src/elem-factory.js, src/styles/_reboot.scss, src/styles/_variables.scss, src/styles/utility/_borders.scss, src/utils/componentry.js, src/utils/componentry.spec.js
=> Chore: Naming improvements

package.json, src/Alert/Alert.js, src/Card/Card.js, src/Close/Close.js, src/Close/close.scss, src/FormGroup/FormGroup.js, src/Input/Input.js, src/Modal/Modal.js, src/Popover/Popover.js, src/Tabs/Tabs.js, src/simple-component-factory.js, src/styles/_variables.scss
Use a simple component factory where possible for simplicity and size savings.
=> Update: Use simple component where possible 🤩

docs/Architecture.md, package-lock.json, package.json, src/Modal/Modal.tsx, src/utils/class-names.ts, src/utils/element-creator.tsx, src/utils/static-component-builder.tsx, src/utils/types.ts, test/types.tsx
Smaller, faster, and with types 🎉
=> Update: Replace classnames with clsx 🆙

.prettierignore, .renovaterc, CHANGELOG.md, styles/_functions.scss, styles/_mixins.scss, styles/_utility.scss, styles/utility/_alignment.scss, styles/utility/_borders.scss, styles/utility/_display.scss, styles/utility/_embed.scss, styles/utility/_flex.scss, styles/utility/_gradients.scss, styles/utility/_media.scss, styles/utility/_position.scss, styles/utility/_resizable.scss, styles/utility/_screen-readers.scss, styles/utility/_shadows.scss, styles/utility/_sizing.scss, styles/utility/_spacing.scss, styles/utility/_typography.scss, styles/utility/_vertical-align.scss, styles/utility/_visibility.scss, styles/utility/background.scss
_Establishes the baseline of changes for 3.5 release_
=> Chore: Establish baseline changes for 3.5

jest.config.js, src/Badge/Badge.stories.mdx, src/List/List.stories.mdx
Adjusts the Jest test coverage configs to reflect recent updates.
=> Chore: Adjust test coverage matches

package-lock.json, package.json, src/components/Alert/Alert.styles.ts, src/components/Button/Button.styles.ts, src/components/Close/Close.styles.ts, src/components/Icon/Icon.styles.ts, src/components/Link/Link.styles.ts, src/components/Text/Text.styles.ts, src/plugin-postcss/configs.ts, src/plugin-postcss/plugin.ts, src/theme-defaults.ts
_Adds merging of library and user configs_
- Uses `cosmiconfig` to look up a Componentry theme.
- Merges component styles.
=> New: Merge user configs

src/components/Alert/Alert.tsx, src/components/Button/Button.ts
_Provide module augmentation for Button and Alert_
=> Update: Add module augmentation for Alert and Button

src/Intro.stories.mdx, src/components/Popover/Popover.stories.mdx, src/components/Tooltip/Tooltip.stories.mdx
_Small Storybook improvements for developing._
=> Docs: Update Storybook intro and screenshot Tooltip/Popover

.npmignore, package.json
_Updates the tags and ignore configs for npm publishing._
=> Configs: Update npm publishing configs

src/components/Button/Button.ts, src/plugin-postcss/plugin.ts, src/test/types.tsx, src/utils/utility-classes.ts
_Beta testing fixes_
- Fix default Button size type to match default classes
- Fix `utilityClasses` type signature to allow usage with exported `UtilityProps` type
- Fix missing source-map from PostCSS plugin processing
=> Fix: Beta fixes for utility types and PostCSS source maps

src/components/Grid/Grid.ts, src/utils/utility-classes.ts
_Adds `justifyItems` and `justifySelf` props_
- Updates Grid to map `justify` shorthand to `justifyItems` for hopefully more intuitive behavior
=> Upgrade: Add addl justify utility props

src/components/Alert/Alert.styles.ts, src/components/Badge/Badge.styles.ts, src/components/Button/Button.styles.ts, src/components/Card/Card.styles.ts, src/components/Close/Close.styles.ts, src/components/FormGroup/FormGroup.styles.ts, src/components/Icon/Icon.styles.ts, src/components/Link/Link.styles.ts, src/components/Text/Text.styles.ts, src/plugin-postcss/plugin.ts
_Consistently use names across files_
=> Match component naming style across files

src/components/Text/Text.ts
_Provides much more convenient text element definitions._
=> Merge custom text elements map with library defaults

package-lock.json, package.json, src/plugin-postcss/configs.ts, src/plugin-postcss/plugin.ts, src/utils/merge.spec.js, src/utils/merge.ts
_Simplify dependencies by using an in-repo merge fn_
=> Use simple merge fn

src/utils/utility-classes.spec.js, src/utils/utility-classes.ts, tailwind.config.js
_Adds utility props for a few more styles_
=> Adding utility props

src/components/Card/Card.styles.ts, src/components/Input/Input.styles.ts, src/components/Modal/Modal.styles.ts, src/components/Popover/Popover.styles.ts, src/components/Table/Table.styles.ts, src/theme-defaults.ts, src/utils/foundation.styles.ts, src/utils/utility-classes.ts, tailwind.config.js
Out of the box Componentry matches TW's border classes with the `borderWidth`, `borderColor` and `borderStyle` utility props. If you're using their Preflight styles you can add borders to any element with a `borderWidth` value.
Alternatively you can use semantic border styles with the `border` theme and matching utility prop. This lets you setup semantic borders like: `{ focused: '1px solid #bfdbfe' }`. This requires setting up a custom Tailwind plugin, and doesn't support color/width overrides without using important, but some teams will find the semantic narrowing of options more useful.
Closes #428
=> Update: Create a cohesive border styling API

src/components/Flex/Flex.ts, src/utils/utility-classes.spec.js, src/utils/utility-classes.ts
_More closely mirror CSS style._
- Change align content and justify content values with `space-
=> Update: Use more precise utility prop value for justify/align

src/theme/theme-defaults.ts, src/utils/utility-classes.ts
_Removes an odd step in the spacing scale._
=> Remove odd step from spacing scale

src/api-types.ts, src/components/Button/Button.spec.js, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.spec.js.snap, src/components/IconButton/IconButton.spec.js, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.styles.ts, src/components/IconButton/IconButton.tsx, src/components/IconButton/__snapshots__/IconButton.spec.js.snap, src/components/Provider/Provider.tsx, src/plugin-postcss/plugin.ts
_Adds IconButton to the components_
- Provides a fully customizable component for wrapping icons to create accessible action elements
=> New: Add IconButton component

src/components/Block/Block.stories.mdx, src/components/Paper/Paper.spec.js, src/components/Paper/Paper.stories.mdx, src/components/Paper/Paper.styles.ts, src/components/Paper/Paper.tsx, src/components/Paper/__snapshots__/Paper.spec.js.snap, src/components/Provider/Provider.tsx, src/plugin-postcss/plugin.ts
_Add Paper component for creating consistent containers for custom elements._
=> New: Add Paper component

src/index.ts
_Fix missing Paper exports from library index._
=> Fix: Add Paper exports to index

src/components/Alert/Alert.tsx, src/components/Badge/Badge.ts, src/components/Button/Button.tsx, src/components/IconButton/IconButton.tsx, src/test/types.tsx
_Fixes an issue where some components had the incorrect type for custom color props._
=> Fix: Types for color props

.eslintrc.js, src/components/Block/Block.ts, src/components/Button/Button.tsx, src/components/Card/Card.ts, src/components/Close/Close.tsx, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.ts, src/components/Paper/Paper.ts, src/components/Popover/Popover.tsx, src/components/Provider/Provider.tsx, src/components/Text/Text.ts, src/components/Text/__snapshots__/Text.spec.js.snap, src/plugin-babel/__fixtures__/data-precompiled/output.js, src/plugin-babel/__fixtures__/expression-containers/output.js, src/plugin-babel/__fixtures__/passthrough-props/output.js, src/plugin-babel/__fixtures__/spread-attribute/output.js, src/plugin-postcss/configs.ts, src/test/types.tsx, src/utils/utility-classes.ts
_Make component types polymorphic based on `as` prop._
- If needed provide context with additional notes...
=> Upgrade: Polymorphic types

src/components/Button/Button.spec.js, src/components/Button/Button.stories.mdx, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.spec.js.snap, src/components/IconButton/IconButton.spec.js, src/components/IconButton/IconButton.tsx, src/test/types.tsx
_Support using IDs to include icons in buttons._
- Convenient shorthand ability for including icons using the system components.
=> Upgrade: Support string icon IDs in buttons

src/components/Block/Block.ts, src/components/Button/Button.tsx, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.ts, src/components/Paper/Paper.ts, src/components/Text/Text.ts
Small organizational improvement.
=> Docs: Move JSDoc to type definitions

package-lock.json
_Create a fresh lockfile after all the deps updates to make sure everything is up to date._
=> Chore: Save a fresh lockfile

src/utils/utility-classes.ts
_Clarifies the value branching in utility styles_
- This isn't technically necessary but could easily be misinterpreted as a bug, explicit branching improves readability === improves maintainability.
=> Update: Clarify code branching in utility styles

src/plugin-babel/__fixtures__/classname-props/code.js, src/plugin-babel/__fixtures__/classname-props/output.js, src/plugin-babel/__fixtures__/data-precompiled/output.js, src/plugin-babel/__fixtures__/transforms-components/code.js, src/plugin-babel/__fixtures__/transforms-components/output.js, src/plugin-babel/plugin.spec.js, src/plugin-babel/plugin.ts, src/plugin-babel/prepare-attributes.ts
_Adds support for arbitrary className values in pre-compilation._
Closes #492
=> New: Support arbitrary className values in pre-compilation

src/components/Alert/Alert.styles.ts, src/components/Badge/Badge.styles.ts, src/components/Card/Card.styles.ts, src/components/Close/Close.styles.ts, src/components/FormGroup/FormGroup.styles.ts, src/components/Input/Input.styles.ts, src/components/Modal/Modal.styles.ts, src/components/Paper/Paper.styles.ts, src/components/Popover/Popover.styles.ts, src/components/Table/Table.styles.ts, src/components/Tooltip/Tooltip.styles.ts, src/config/config.ts
_Types the remaining style files._
=> Update: Type remaining styles

src/index.ts
_Export the config type for declaring configs to get IntelliSense_
=> Update: Export Config type

src/api-types.ts, src/components/Badge/Badge.spec.js, src/components/Badge/Badge.stories.mdx, src/components/Badge/Badge.styles.ts, src/components/Badge/Badge.ts, src/plugin-babel/__fixtures__/transforms-components/code.js, src/plugin-babel/__fixtures__/transforms-components/output.js, src/plugin-babel/plugin.ts
=> Update: Badge ready for production use

src/index.ts, src/plugin-babel/__fixtures__/component-props/code.js, src/plugin-babel/__fixtures__/component-props/output.js, src/plugin-babel/parse-attributes.ts, src/utils/utility-classes.spec.js, src/utils/utility-classes.ts
Badge component updates:
1. Bugfix Badge props not being included in Babel plugin transforms
2. Export BadgeProps type from library
3. Add shorthand `radius` utility class
=> Badge: Updates and bug fixes for Badge component

package.json, pnpm-lock.yaml, src/test/types.tsx, src/theme/theme-defaults.ts, src/utils/utility-props.ts
_Summary of PR changes..._
- If needed provide context with additional notes...
=> Type updates
