crystal-ball/componentry

lib/Nav/NavItem.jsx, lib/Nav/NavItem.spec.jsx
ISSUES CLOSED: #4
* 🐛 Fixes classname props not being passed through to the `<NavItem />` component.
* ✅ Added tests for NavItem component
=> fix(components): ensure context and props classnames are passed through

lib/Popover/Popover.js, lib/Popover/__snapshots__/Popover.spec.jsx.snap, lib/Popover/popover.scss, lib/Tooltip/Tooltip.js, lib/Tooltip/__snapshots__/Tooltip.spec.jsx.snap, lib/Tooltip/tooltip.scss, lib/component-factories/active-content.jsx, lib/utils/dom.js, src/components/ComponentsScreen/PopoversScreen/Popovers.md, src/components/ComponentsScreen/TooltipsScreen/Tooltips.md
ISSUES CLOSED: #10 
Poppers now use a content container to create a positioned ancestor with width equal to popper max, this allows removal of hacky width calculations within the content component to get the correct display width.
=> refactor(components): wrap poppers in content container 🔨

demo/styles/theme.scss, src/Popover/popover.scss
Fixes alignment of the popover content for direction left popovers without content that fills the
max-width. Also includes cleaned up styles for creating popover tips.
=> fix(components): fix popover alignment styles 👍

styles/componentry/_icons.scss
This extend is no longer needed now that there are icon styles in the library
=> fix(styles): remove invalid and unnecessary extend 👍

.babelrc.js, package-lock.json, package.json
Jest isn't updated to Babel 7 and requires the bridge package for now.
=> chore: updates to get Jest working with Babel 7

.prettierignore, demo/styles/application/app.scss, demo/styles/theme.scss, src/Button/button.scss, styles/theme/_button.scss, styles/theme/_variables.scss
Adds a new feature: `$btn-bg-states` which is a map that allows users to override specific button backgrounds for a specific state. This is especially useful if you don't want the exact same color darkening for each theme color.
=> feat: add btn-bg-states override mechanism

src/Anchor/anchor.scss, src/Header/Header.js, src/Header/header.scss, src/Text/Text.js, src/Text/text.scss, styles/_reboot.scss
Follows the library convention of using utility class names to apply styles whenever possible
=> New: Scope anchor and header styles to className only ✨

docs/TODO.md, src/components/Alert/Alert.tsx, src/components/Badge/Badge.ts, src/components/Block/Block.ts, src/components/Button/Button.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/Input/Input.tsx, src/components/Link/Link.ts, src/components/List/List.ts, src/components/Modal/Modal.tsx, src/components/Nav/Nav.ts, src/components/Tabs/Tabs.ts, src/components/Text/Text.ts, src/plugin-babel/plugin.ts, src/utils/active-action-component-builder.tsx, src/utils/active-container-component-builder.tsx, src/utils/active-content-component-builder.tsx, src/utils/componentry.spec.js, src/utils/element-creator.tsx, src/utils/static-component-builder.tsx, src/utils/style-utilities.ts
_Semantic update to use "Utilities" everywhere._
Closes #363 
System props was aligning towards Styled System and MUI, but aligning with Tailwind is a higher priority and "Utility styles" is a more conventional name for these classses.
=> Update: Rename 'System' to 'Utilities'

src/components/Alert/Alert.stories.mdx, src/components/Alert/Alert.styles.ts, src/components/Link/Link.styles.ts
_Fixes a few small style issues in Alert_
- Removes default theme colors for alert - currently these will throw an error if theme colors haven't been defined.
- Improves link styles - in and out of Alerts
=> Fix: Default alert theme styles

.storybook/storybook-styles.css, src/components/Close/Close.stories.mdx, src/components/Close/Close.styles.ts, src/plugin-postcss/plugin.ts
_Adds a new rollup style option_
Provides a `@componentry components;` rollup option for including all component styles. This is a convenience option if you're using all of the components.
Closes #382
=> New: Convenience components rule

src/index.ts, src/utils/utility-classes.ts
_Exposes `utilityClasses`_
Enables users to create their own custom design system components with support for the standard utility props.
Closes #383
=> New: Expose utilityClasses fn

.babelrc.js, src/components/Block/Block.ts, src/components/Card/Card.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Text/Text.ts, src/components/Theme/Theme.tsx, src/plugin-babel/parse-attributes.ts, src/plugin-babel/plugin.ts, src/utils/types.ts, src/utils/utility-classes.ts
_Replaces mechanism for skipping theme context during Babel pre-compilation._
- The `__precompile` prop that had to be passed for each component was not "elegant" and could be confusing for package users.
- Updated mechanism allows for notifying the theme module during pre-compiling to skip using React context
=> Update: Replace __precompile prop

src/components/Active/Active.ts, src/components/Alert/Alert.tsx, src/components/Badge/Badge.ts, src/components/Block/Block.ts, src/components/Button/Button.ts, src/components/Card/Card.ts, src/components/Close/Close.tsx, src/components/Drawer/Drawer.ts, src/components/Dropdown/Dropdown.ts, src/components/Flex/Flex.ts, src/components/FormGroup/FormGroup.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/Input/Input.tsx, src/components/Link/Link.ts, src/components/Modal/Modal.tsx, src/components/Popover/Popover.tsx, src/components/Table/Table.ts, src/components/Tabs/Tabs.ts, src/components/Text/Text.ts, src/hooks.ts, src/index.ts, src/utils/active-action-component-builder.tsx, src/utils/active-container-component-builder.tsx, src/utils/active-content-component-builder.tsx, src/utils/aria.ts, src/utils/element-creator.tsx, src/utils/types.ts, src/utils/utility-classes.ts
_Updates the exposed types from the library to enable creating custom components with `utilityStyles`._
Closes #387 
- Module augmentation exports now include "overrides" in their name for explicitness
- Merged utility types type is exported for use with `utilityStyles`
- Updated imports to use `type <TYPE>` syntax for clarity
=> Update: Expose correct utility types

src/utils/types.ts
Fixes this compiler error:
```
Exported variable 'Button' has or is using name 'UtilityPropsDefaults' from external module "/componentry/src/utils/types" but cannot be named.
```
=> Fix: Compiler error of 'cannot be named'

.babelrc.js, package-lock.json, package.json
After some research it seems that most libraries do not include polyfills from Babel+core-js in their outputs. PR removes the corejs configs from Babel to fix broken build.
=> Fix: Compilation configs polyfill fixes

package-lock.json, package.json
_Loosens package dependencies to allow consumers more control over versions_
- Open `dependencies` to semver major, allowing consumers to control deps better, eg nanoid 3.3 or 3.2 can be used.
=> Deps: Loosen package dependencies

.storybook/storybook-styles.css, src/components/Icon/Icon.spec.js, src/components/Icon/Icon.tsx, src/components/Text/Text.spec.js, src/components/Text/Text.ts, src/index.ts
_Upgrade to provide a consistent element setup for Icon and Text_
- Both components export a "configure elements map" function that can be called during library setup from anywhere to define the map of elements to render for each variant/id.
=> Upgrade: Add dedicated setup mechanism for elements

.eslintignore, babel.js, docs/publishing.stories.mdx, package.json, postcss.config.js, postcss.js, src/plugin-babel/index.ts, src/plugin-postcss/index.ts, tsconfig.json
_Improvements to the package export definitions_
- Turns out getting all of the export configurations right is tricky 😄 
- Adds back `main` and `module` for backwards compat, `eslint-plugin-import` needs them.
- Figured out a way to include Babel/PostCSS plugin entries in their src folders
=> Upgrade package export definitions

jest.config.js, src/benchmarks/utility-classes.benchmark.ts, src/benchmarks/v1-utility-classes.ts, src/plugin-babel/plugin.ts, src/utils/utility-classes.spec.js
Replaces the mechanism for computing utility classes: Switches from using an object with `clsx` to a switch statement. Overall result is _MUCH_ faster 🏎️ 
Benchmark performance in ms
| V1: Object w/ clsx |        |        | V2: Switch       |                  |                  |
| ------------------ | ------ | ------ | ---------------- | ---------------- | ---------------- |
| Large              | Small  | Total  | Large            | Small            | Total            |
| 1627               | 1533   | 3161   | 116              | 32               | 148              |
| 1644               | 1528   | 3172   | 105              | 29               | 134              |
| 1667               | 1516   | 3184   | 104              | 29               | 133              |
| 1632               | 1565 …
=> Use switch statement for perf in createUtilityClasses

src/plugin-postcss/configs.ts
_Updates the PostCSS plugin to use the passed theme directly._
This consolidates theme definition for users to a single location, preferably using `createTheme`, and then using that same created theme value for the PostCSS plugin as well as the runtime `useTheme`.
=> Update: Use passed theme directly for PostCSS

src/components/Block/Block.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/Provider/Provider.tsx, src/index.ts, src/test/types.tsx
Provide ref-able versions of Block,Flex,Grid
- Useful for creating layouts with ResizeObservers or hooks that measure dimensions.
=> New: Provide ref-able layout components

src/theme/theme-defaults.ts
_Fixes `flexGrow` and `flexShrink` not working as boolean values._
=> Fix: flexGrow and flexShrink default values

src/components/Block/Block.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Text/Text.ts, src/index.ts, src/plugin-babel/__fixtures__/basics/code.js, src/plugin-babel/__fixtures__/basics/output.js, src/plugin-babel/__fixtures__/refs/code.js, src/plugin-babel/__fixtures__/refs/output.js, src/plugin-babel/plugin.spec.js, src/plugin-babel/plugin.ts, src/test/types.tsx
_Upgrades the Babel plugin to work with ref-components._
- Block, Flex, Grid, and Text now accept refs
- Performance overhead from refs is assumed to be at least partially offset by pre-compiling these elements.
=> New: Support precompiling forwardRef components

src/api-types.ts, src/components/Button/Button.styles.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/Link/Link.styles.ts, src/components/Text/Text.ts
_Adds Button and Link types to the API docs types._
- Renames original Block/Flex/Grid "base" props to match more frequent "defaults" props
=> API Docs: Add Button and Link types

src/components/Block/Block.ts, src/components/Button/Button.ts, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/Link/Link.ts, src/components/Provider/Provider.tsx, src/components/Text/Text.ts, src/test/types.tsx
_Provides better IntelliSense for all components_
**Before**
This type isn't readable and distracts from any other docs
**After**
Streamlined type lets other docs info shine
=> Docs: Upgrade TSDoc and type display

src/theme/theme-defaults.ts, src/utils/types.ts, src/utils/utility-classes.ts
_Very fun little update that updates the utility props dependent on theme values to be computed from those theme values._
- This is intended to reduce the amount of type definitions and duplicated setup code Componentry requires.
=> New: Derive utility props from theme

.storybook/storybook-styles.css, src/components/Button/Button.stories.mdx, src/components/Button/Button.styles.ts, src/components/Button/Button.tsx, src/plugin-postcss/configs.ts, src/test/types.tsx
_Adds support for icons to Button and improves API for disabled buttons_
Closes #376 
- Add `startIcon` and `endIcon` props
- Add `wrapWhenDisabled` prop
=> Button icons

.storybook/storybook-styles.css, src/components/Button/Button.styles.ts, src/plugin-postcss/plugin.ts, src/styles/foundation.styles.ts, src/styles/states.styles.ts
_Improve library styles system for component states._
Closes #279 
- Adds Componentry `@utilities` import
- Sets all library disabled elements to `pointer-events: none`
- Adds a themed `:focus-visible` style to Foundations
- If needed provide context with additional notes...
=> Update: Better focus styles

src/components/Button/Button.styles.ts, src/components/Button/Button.tsx, src/components/Link/Link.stories.mdx, src/components/Link/Link.styles.ts, src/components/Link/Link.tsx, src/components/Tabs/__snapshots__/Tabs.spec.js.snap, src/theme/theme-defaults.ts
_Update Link to match Button disabled patterns_
- Add `wrapWhenDisabled` to Link
- Add text color and font-size `inherit` to theme
- Update Link variant to `text` only, using `inherit` as default.
=> Update: Handle disabled patterns in Link

src/components/Button/Button.tsx, src/components/Link/Link.tsx
_Fixes a bug where using a ActionRoot component to support a `to` would result in anchor tags with `type="button"`_
- Supporting by checking for `to` in each component instead of using a shared base component, this is the only logic and it's easier to duplicate.
=> Fix: Incorrect type when using 'to' with Button/Link

src/components/Button/Button.stories.mdx, src/components/Button/Button.styles.ts, src/components/Button/Button.tsx, src/components/IconButton/IconButton.spec.js, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.tsx, src/index.ts, src/test/types.tsx
Includes a number of API upgrades for working with Buttons and Icons
- Props startIcon, endIcon, and icon all require a ReactElement now
- Button icons have classes `C9Y-Button-icon`, `C9Y-Button-startIcon`, and `C9Y-Button-smallSizeIcon`
- ButtonIcon type checks for `to`
=> Update: Icon related Button upgrades

package.json
_Fixes an issue where the library fails in Jest v28_
- See: https://jestjs.io/docs/upgrading-to-jest28#packagejson-exports
- See: https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#conditional-exports
=> Fix: Include require import for browsers for Jest 28

src/components/Button/Button.stories.mdx, src/components/Button/Button.tsx, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.tsx, src/components/Tabs/__snapshots__/Tabs.spec.js.snap
_Removes the `wrapWhenDisabled` prop and elements from Button, IconButton, and Link_
BREAKING CHANGE:
This wrapping element was intended to make the action components "work out of the box" with libraries like MUI/Chakra-UI which require wrapping disabled buttons in a span. Because it's not working as intended it's being removed to keep these elements as simple as possible.
As an alternative consuming libraries can create their own wrapper components around buttons and links to handle auto-support for disabled elements and tooltips.
=> Remove wrapWhenDisabled prop from action elements

.eslintrc.js, src/components/Block/Block.ts, src/components/Button/Button.tsx, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.ts, src/components/Paper/Paper.ts, src/components/Text/Text.ts, src/test/types.tsx, src/utils/types.ts
_Improves the new polymorphic types to work when extending components._
Examples of this added in the types test file, patterns like this now type check correctly:
```tsx
// Should be able to "extend" a component by wrapping it and using the exported component's props type.
function ExtendedText(props: TextProps) {
return <Text {...props} className='OVERRIDE' />
}
// Should be able to create a generic extended component that also supports `as` usage
function GenericExtendedText<Elem extends React.ElementType = 'div'>(
props: TextProps<Elem>,
) {
return <Text {...props} className='OVERRIDE' />
}
```
=> Update: Improved polymorphic types that support extending components

src/components/Button/Button.tsx, src/components/IconButton/IconButton.tsx
_Fix a regression for color prop type in Button and IconButton._
- Deleted during polymorphic types update
=> Fix: Omit UtilityProp color from Button components

src/components/Icon/Icon.tsx
_Widen component type to resolve type errors from component props._
=> Fix: Widen component type in IconElementsMap

src/components/Block/Block.ts, src/components/Button/Button.tsx, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.ts, src/components/Paper/Paper.ts, src/components/Text/Text.ts
_Removes inaccurate return type of `null` from component type definitions._
These components always return a ReactElement.
=> Update: Remove components' null return type

src/components/Text/Text.spec.js, src/components/Text/Text.ts, src/index.ts, src/plugin-babel/parse-attributes.ts, src/theme/theme-defaults.ts
_Move textElementMap to Text props_
- Enables defining text variants in the application config, which allows a single Babel config
=> Update: Move textElementMap to props

.eslintrc.js, src/plugin-babel/__fixtures__/checks-import-paths/code.js, src/plugin-babel/__fixtures__/checks-import-paths/output.js, src/plugin-babel/plugin.spec.js, src/plugin-babel/plugin.ts
_Update the Babel precompile plugin to include import path checking and successful precompile rate stats_
- Before precompiling a component the plugin will now check that it was imported from Componentry. This helps guard against components with the same names as Componentry precompile elements that should _NOT_ be transformed.
- Add a `customImportPath` option to the plugin for configuring an additional module that should mark components as compileable.
- Adds a success rate stats logging step when `debug` is enabled.
=> New: Babel plugin custom import path and transform stats

src/plugin-babel/__fixtures__/exclude_option/code.js, src/plugin-babel/__fixtures__/exclude_option/output.js, src/plugin-babel/plugin.spec.js, src/plugin-babel/plugin.ts
_Adds an `exclude` option to the Babel plugin for components that should not be precompiled._
- This is useful for consumers that want to create their own version of components
=> Add exclude option to Babel plugin

src/components/Badge/Badge.ts, src/components/Block/Block.ts, src/components/Button/Button.tsx, src/components/Flex/Flex.ts, src/components/Grid/Grid.ts, src/components/Icon/Icon.tsx, src/components/IconButton/IconButton.tsx, src/components/Link/Link.ts, src/components/Paper/Paper.ts, src/components/Text/Text.ts, src/index.ts, src/test/types.tsx, src/utils/types.ts, src/utils/utility-props.ts
_Simplifies the pattern for component prop types and exposes an `ElementTypeProps` utility type for creating custom components._
- Replaces the previous pattern for component prop types which required the very complex `DistributiveOmit` utility type as well as multiple layers of type generics in order to get component polymorphism to work.
- The updated pattern provides a simpler single layer generic type to create a component prop type.
=> Update: Simplified type utilities exported
